name: Microsoft SQL Server 2017 (Remote Storage)
description: |
  Microsoft SQL Server 2017 for Linux using a storage driver from Rancher
version: RC2
category: Databases
maintainer: Rich Bayliss
license: Microsoft
projectURL: https://hub.docker.com/r/microsoft/mssql-server-linux/