name: Microsoft SQL Server 2017
description: |
  Microsoft SQL Server 2017 for Linux
version: RC2-Local
category: Databases
maintainer: Rich Bayliss
license: Microsoft
projectURL: https://hub.docker.com/r/microsoft/mssql-server-linux/