name: Microsoft SQL Server 2017 (Local Storage)
description: |
  Microsoft SQL Server 2017 for Linux usig local disks for storage
version: RC2
category: Databases
maintainer: Rich Bayliss
license: Microsoft
projectURL: https://hub.docker.com/r/microsoft/mssql-server-linux/